### ISSUE TITLE
Safari - Problème de recherche

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#100]
Donovan sous Mac avec Safari recherche TOUT avec taxon "Lagopède alpin" entre 1900 et 2015 et ça ne lui renvoie aucun résultats. Moi ça m'en retourne bien 2850 sur PC avec Chrome...
Et ça marche sur son MAC avec Firefox... Donc problème Safari ???

**Comment by gildeluermoz** [comment]
Est-ce que Donovan peut retester et me dire si le pb persiste ?

**Comment by Donovan-PNE** [comment]
Bonjour (et bonne année), 

Après un accès un peu compliqué à géonature (page blanche, puis ensuite résultats très longs à venir), j'ai bien des résultats pour le lagopède, que je recherche dans TOUT ou dans FAUNE. 

Merci!

**Comment by gildeluermoz** [comment]
Merci Donovan pour le test. Je ferme le ticket et je vais regarder les soucis de lenteurs. J'ai une idée sur le sujet ; c'est probablement relatif à la modification permettant d'afficher tous les synonymes.
