### ISSUE TITLE
Export XLS - décalage de colonnes

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature#108]
ex : données gypaëte 2015

**Comment by gildeluermoz** [comment]
Vérifier le soucis selon les versions des tableaux et les options de séparateurs cochées pour ouvrir le fichier xls

**Comment by camillemonchicourt** [comment]
Passer au format CSV et plus ce fucking XLS ? :-)

**Comment by gildeluermoz** [comment]
Why not ! Mais le csv ne s'ouvre pas directement depuis le navigateur. De nombreux agents ne savent pas l'utiliser. 
Je ne suis pas trop pour. Pourquoi pas un param de config pour générer du csv ou de l'xls. Mais ça reste à évaluer. 
Non prioritaire

**Comment by camillemonchicourt** [comment]
OK
