### ISSUE TITLE
EXPORT XLS - Nom valide contient balise HTML

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#111]
<i> On peut les virer de l'export ?

**Comment by gildeluermoz** [comment]
Oui on peut mais doit-on ? Le champ est livré tel que dans le taxref.

**Comment by gildeluermoz** [comment]
le soucis vient de la base de donnée, table ``taxonomie.taxref`` mal remplie pour le champ nom_valide.
A corriger en base
