### ISSUE TITLE
EXPORT OBSERVATIONS - Vide

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#113]
Certaines recherches fonctionnent mais l'export XLS des observations est vide. 
Rechercher sur les bouquetins 2015 par exemple. Ou même uniquement sur décembre 2015.

**Comment by gildeluermoz** [comment]
je n'arrive pas à reproduire ce bug

**Comment by camillemonchicourt** [comment]
Non reproduit par l’utilisateur.

**Comment by camillemonchicourt** [comment]
Michel Bouche, sous Firefox, il n'arrive pas à exporte sous les XLS les observations.

Par ailleurs, il peuvent modifier et supprimer TOUTES les observations alors qu'il est reconnu comme un rédacteur.

Même après avoir vidé le cache.

Pas de problème sur Chrome.

Donc même problème que celui de RODOLPHE ? Que dans Firefox ?

**Comment by gildeluermoz** [comment]
Un redémarrage du navigateur semble résoudre le pb. Test concluant avec Michel Bouche.
Le pb semble donc venir du navigateur. Sinon pb aléatoire difficilement reproductible pour le résoudre.
