### ISSUE TITLE
SYNTHESE - Liste des taxons en latin ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#116]
Problème dans la liste des taxons français avec des taxons en latin.

**Comment by camillemonchicourt** [comment]
C'est du au fait que certains taxons n'ont pas de nom français. 
Dans ce cas là je penche quand même pour ne lister que les taxons français dans la liste TAXONS FRANÇAIS. 
Si on choisit un taxon en latin qui n'a pas de nom français, alors on laisse le champs vide.

**Comment by gildeluermoz** [comment]
Cette modification impacte fortement le fonctionnement de GeoNature.
En effet afin de permettre le switch entre le nom latin et le nom français dans la liste des taxons sur les application mobile, si le nom francais n'existe pas, il n'a pas été prévu de fonctionnement dans ce cas.
La vue qui remonte la liste des taxons pour les mobiles doit donc comporter une valeur pour le nom latin ET pour le nom français sinon l'application mobile en mode "FR" afficherait des lignes vides (cas de la plupart des invertébrés". Donc dans la liste des taxons, si le nom français n'existe pas, j'ai mis le nom latin.
Pour corriger ce comportement dans la synthese de GeoNature, je dois créer 2 stores (un fr, l'autre latin) pour alimenter séparément chacun des combobox latin et fr. Dans le store fr je supprime tous les taxons dont le nom français n'existe pas.
J'ai également revu le lien gérant le comportement de ces deux combobox.

**Comment by gildeluermoz** [comment]
Au passage, suppression dans la vue ``synthese.v_taxons_synthese`` des taxons enregistrés dans la synthèse puis supprimés (aucune observation conservée).
