### ISSUE TITLE
INVERTEBRES - Bug sur le filtrage des mollusques

### ISSUE THREAD

**Issue by xavier-pnm** [PnEcrins/GeoNature#128]

**Comment by gildeluermoz** [comment]
Il y a dans les listes, les gastéropodes (8) et les bivalves (10) mais aussi les mollusques (101).
Le soucis c'est que les filtres dans le mobile sont développés sur la base d'id_classe en dur dans le code, et avec une distinction entre les gastéropodes et les bivalves alors que GeoNature web parle de mollusques en général. Mais les deux applications utilisent la même vue : contactinv.v_nomade_classe. 
Or si on met les 3 classes 8,10 et 101 dans la vue, on va avoir des doublons dans les listes de taxons.
Il faut donc faire un choix et comme on ne peut pas modifier le code coté mobile, on est obligé de modifier GeoNature web.
Les bivalves étant marginaux, j'ai donc fait le choix de ne retenir que les gastéropodes dans GeoNature web.
