### ISSUE TITLE
Doublons d'affichage des noms d'utilisateurs dans les listes des formulaires de saisie

### ISSUE THREAD

**Issue by xavier-pnm** [PnEcrins/GeoNature#130]
Quand des utilisateurs sont affectés à la fois à un groupe (ex : agents en postes) et à une liste (ex : observateurs faune), ils sont listés 2 fois dans le champ observateurs (ne peuvent cependant pas être sélectionnés plus d'une fois). (manque une clause 'distinct' ou 'union').

**Comment by gildeluermoz** [comment]
Je ne parviens pas à reproduire l'erreur.
J'ai un utilisateur "test" qui est dans le groupe "grp_en_poste". 
Dans la liste "faune-observateurs", je mets le groupe "grp_en_poste" et l'utilisateur "test". J'enregistre.
Si je vais dans le formulaire de saisie contact-faune, l'utilisateur test n'apparait qu'une fois.
Pourrais-tu me donner un contexte précis où ce doublonnage se produit ?

**Comment by camillemonchicourt** [comment]
@xavier-pnm, bug confirmé ?

**Comment by xavier-pnm** [comment]
Négatif, je n'ai plus le problème désormais.
