### ISSUE TITLE
Ajouter champs DIFFUSION dans synthese.syntheseff

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#132]
Comme discuté en interparc le 23/05/2016. 

Permet de mentionner si une observation est diffusable ou non. Notamment pour la publier dans l'atlas ou non. Mais aussi pour la diffuser à des partenaires ou non. 

> Question de la sensibilité des données : est ce qu'on le gère au niveau du taxon ou au niveau de l'observation ? 
> Le PNC souligne que juridiquement, c'est plutôt au niveau de l'observation, mais pour autant ce n'est pas à l'observateur de le décider au moment de la saisie. La solution serait de rajouter un champs dans la synthèse de GeoNature qui est rempli par l'administrateur. Cette information permettra à l'atlas de totalement masquer une observation ou de la dégrader.

A nommer `Diffusion`, `Public`, `Sensible` ? Je pencherai pour `Diffusion`.

Booléen OUI/NON ou liste de valeur pour avoir OUI/DEGRADE/NON ? Je pencherai pour un booléen OUI/NON.

**Comment by gildeluermoz** [comment]
C'est bien au niveau de l'obs qu'il faut le faire.
Ok pour ajouter un champ dans geonature (dans syntheseff)
je penche pour ``sensible`` car c'est le terme officiel.
Oui pour le boolean default = false. Dans un premier temps baculer les obs à true en admin si besoin.
La notion de dégradation ou de ne pas du tout l'afficher est un choix d'usage. Je penche pour ne pas afficher ces données.

**Comment by camillemonchicourt** [comment]
Pour être clean, il faudrait que cela soit fait dans les BDD des protocoles et répercuté dans `synthese.syntheseff` en complétant les triggers. 
Dans un premier temps, ne faire que les modifications en BDD, mais pas dans les interfaces de saisie. 

Pour le terme, `Sensible` est peut-être mieux et plus clair en effet, mais la notion de sensibilité est plus complexe qu'un booléen et s'appuie sur une justification.

**Comment by gildeluermoz** [comment]
Fait uniquement en synthèse pour le moment. Donc toute modification de la valeur de ce champ doit être faite en SQL avec des outils administrateur. Pas d'outil dans GeoNature pour faire ça.
