### ISSUE TITLE
CONTACTS : Auto-remplissage du nom d'observateur ne fonctionne pas toujours

### ISSUE THREAD

**Issue by xavier-pnm** [PnEcrins/GeoNature#134]
Lors de l'initialisation du formulaire de saisie dans les protocoles de contacts, le nom d'observateur principal n'est pas systématiquement renseigné automatiquement d'après le login de connexion (parfois vide). Comportement assez aléatoire selon les vitesses d'exécution des scripts...

**Comment by camillemonchicourt** [comment]
@xavier-pnm, bug confirmé ?

**Comment by xavier-pnm** [comment]
Oui je confirme même si ce n'est pas systématique. Peut-être lié à une réponse tardive du serveur pour générer la liste lors de l'activation du formulaire ?

**Comment by camillemonchicourt** [comment]
OK à voir si cela peut être corrigé dans une prochaine 1.X si c'est simple. 
Sinon la V2 refondant tout cela, ça sera corrigé dans la 2.X

**Comment by gildeluermoz** [comment]
Oui c'est un soucis d'asynchronisme dans le chargement des contenus des stores d'Extjs.
Comme c'est complexe et non bloquant, je ne compte pas le corriger. Le soucis n'existera plus dans la V2 avec Angularjs.

**Comment by camillemonchicourt** [comment]
OK
