### ISSUE TITLE
Les chaînes de caractères ne sont pas protégées lors de l'export csv.

### ISSUE THREAD

**Issue by nviel** [PnEcrins/GeoNature#143]
Aucun système ne permet d'échapper les caractères de séparation des champs csv. Du coup, si on écrit un commentaire contenant un ';' le nombre de champs est mal interprété lors de l'import dans un tableur.

Par exemple j'écris "je teste; et ça marche pas" dans le commentaire d'une observation, et lors de l'export SINP le commentaire est coupé en deux.

**Comment by camillemonchicourt** [comment]
En effet ce problème est connu. 
Il faut que l'on ajoute une méthode d'échappement pour éviter cela.

**Comment by gildeluermoz** [comment]
Bien vu. Merci. La correction est faite dans la branche develop pour le moment. 84f23346e84d7cf5e33e61016ea161138a8e508e
Pourriez vous nous dire quelle version vous avez installé (une release ou le master ou le develop) ainsi que votre objectif : test ou production ?
En vous remerciant

**Comment by nviel** [comment]
Oui, désolé, j'aurais du préciser que j'ai juste utilisé la version du site de démo pour connaître un peu le logiciel.

**Comment by gildeluermoz** [comment]
Merci pour votre réponse. N'hésitez pas à nous contacter si vous avez des questions ou un besoin d'approfondissement.
[http://geonature.fr/#contact](url)
