### ISSUE TITLE
Nom des archives ZIP

### ISSUE THREAD

**Issue by sylvain-m** [PnEcrins/GeoNature#159]
Petite suggestion très dérisoire, mais après avoir fait plusieurs extractions de données depuis la synthèse, je constate que les noms des archives ZIP sont au format `synthese_DD_MM_YYYY_hhmmss.ZIP`
Ce qui tri donc les fichiers par jour avant de les trier par années.
En cherchant un peu (pour comprendre !), j'ai constaté que cela se situait dans le fichier "synthese/application.synthese.search.js", où : 
`filename : 'synthese_observations_' + ((new Date()).format('d_m_Y_His'))`
devrait être écrit : 
`filename : 'synthese_observations_' + ((new Date()).format('Y_m_d_His'))`

Rien de très fondamental ;-) , mais du coup, cette simple suggestion pourrait être l'occasion pour moi de découvrir les outils de Github pour participer à l'écriture du code de GeoNature : est-ce que je peux tenter la suggestion ? (je crois que c'est un "pull request", mais je n'en suis même pas sûr)

**Comment by gildeluermoz** [comment]
Oui vas y, fait nous une pull request ! 
Cool, merci 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "sylvain-m" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 7 Février 2017 13:51:23 
Objet: [PnEcrins/GeoNature] Nom des archives ZIP (#159) 


Petite suggestion très dérisoire, mais après avoir fait plusieurs extractions de données depuis la synthèse, je constate que les noms des archives ZIP sont au format synthese_JJ_MM_YYYY_hhmmss.ZIP 
Ce qui tri donc les fichiers par jour avant de les trier par années. 
En cherchant un peu (pour comprendre !), j'ai constaté que cela se situait dans le fichier "synthese/application.synthese.search.js", où : 
filename : 'synthese_observations_' + ((new Date()).format('d_m_Y_His')) 
devrait être écrit : 
filename : 'synthese_observations_' + ((new Date()).format('Y_m_d_His')) 
Rien de très fondamental ;-) , mais du coup, cette simple suggestion pourrait être l'occasion pour moi de découvrir les outils de Github pour participer à l'écriture du code de GeoNature : est-ce que je peux tenter la suggestion ? (je crois que c'est un "pull request", mais je n'en suis même pas sûr)

**Comment by sylvain-m** [comment]
Je viens de tenter ma première "pull request".
J'espère que j'ai fait la bonne procédure : j'ai notamment hésité sur la "branche" à choisir (master / develop).
Merci de votre indulgence ! :)
A+

**Comment by camillemonchicourt** [comment]
Oui ça semble nickel. 
On travaille dans la branche DEVELOP et quand on veut sortir une nouvelle version, on bascule ça dans la branche MASTER mais les PR se font en effet habituellement dans la branche MASTER donc impeccable.

**Comment by gildeluermoz** [comment]
Merci Sylvain, 
De mon coté je préfère les PR dans le develop, ça évite d'avoir à faire des merge dans els deux sens et d'éventuels conflit. J'en parle avec Camille pour savoir pourquoi il pense que les PR se font de le MASTER, je ne comprends pas la logique. 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Mardi 7 Février 2017 15:19:03 
Objet: Re: [PnEcrins/GeoNature] Nom des archives ZIP (#159) 


Oui ça semble nickel. 
On travaille dans la branche DEVELOP et quand on veut sortir une nouvelle version, on bascule ça dans la branche MASTER mais les PR se font en effet habituellement dans la branche MASTER donc impeccable.

**Comment by gildeluermoz** [comment]
closed with https://github.com/PnEcrins/GeoNature/pull/160/commits/f5cc8d743985ccbdc16956c2dcfe9e624eee0d41
