### ISSUE TITLE
Problème protocoles : 'date_insert' et 'date_update' de 'syntheseff' sont vides

### ISSUE THREAD

**Issue by sig-pnrnm** [PnEcrins/GeoNature#165]
Bonjour,

Je ne sais pas si cela vient de notre installation ([lien](http://geonature.readthedocs.io/fr/latest/install_all/2016-12-exemple-deploiement-pnr.html)), ou si le problème est généralisé, mais en explorant les données saisies dans les protocoles GeoNature (Contact-Faune, ...) depuis la stable `synthese.syntheseff`, je constate que les champs `date_insert` et `date_update` sont vides.

Une idée de la cause du problème ?
Merci pour vos conseils !

**Comment by camillemonchicourt** [comment]
On avait peut-être désactivé les triggers pour l'intégration des données et oublié de les réactiver ? 

Tu parles bien des données saisies dans GeoNature ou alors des données importées depuis votre BDD ?

**Comment by sig-pnrnm** [comment]
Effectivement, les triggers étaient desactivés.
Je viens de réactiver les 4 !
Merci pour ton aide.
