### ISSUE TITLE
Flore Bryophytes : écriture noms observateurs inversée

### ISSUE THREAD

**Issue by sig-pnrnm** [PnEcrins/GeoNature#185]
Bonjour,

Je n'avais encore jamais ouvert le protocole "Bryophytes" de notre instance GeoNature.
Suite à la saisie de données par des collègues dans ce protocole, je me suis rendu compte que les noms des observateurs récupérés dans la Synthèse sont écrits au format "Prénom Nom" au lieu de "Nom Prénom" comme depuis les autres protocoles.
Je n'ai pas poussé plus loin l'investigation (je n'ai pas encore bien en tête le circuit des données du schéma du protocole vers celui de la synthèse), mais je suppose que ce n'est pas bien compliqué à corriger et que ce le sera avec la V2, mais au cas où, je préfère le signaler.

J'en profite aussi pour signaler que le bandeau du protocole est très sympa, mais qu'il sera peut-être aussi nécessaire de le rendre plus "générique" ;) : https://github.com/PnEcrins/GeoNature/blob/master/web/images/bandeau_bryo.png

A+

Sylvain

**Comment by sig-pnrnm** [comment]
Si, c'est bon, j'ai trouvé le trigger en question et la correction à apporter : 
`SELECT INTO mesobservateurs array_to_string(array_agg(r.prenom_role || ' ' || r.nom_role), ', ') AS observateurs `
à remplacer par
`SELECT INTO mesobservateurs array_to_string(array_agg(r.nom_role || ' ' || r.prenom_role), ', ') AS observateurs `.
Je vais tenter la modification moi-même

**Comment by sig-pnrnm** [comment]
En espérant ne pas avoir fait d'erreur : 
#186

**Comment by camillemonchicourt** [comment]
Ce protocole a vocation à disparaître dans la V2. 
On a fait ça un peu provisoirement car il y avait un besoin au PNE de saisir des observations de bryophytes et comme il n'y avait pas de CONTACT FLORE à l'époque on avait dupliqué le protocole FLORE STATION (http://geonature.fr/protocoles.html#flore-station) pour cela. 
Aujourd'hui, si vous souhaitez juste faire du Contact Bryophytes, il est préférable de le faire dans le Contact flore que dans l'application Bryophytes qui se base sur le protocole Flore Station et ressemble plus à un relevé phyto qu'à du contact. 

Sinon merci pour la PR, bien vu. 

Ça pose d'ailleurs la question, si dans la V2 on met "Prénom NOM" ou "NOM Prénom" ?

**Comment by sig-pnrnm** [comment]
En effet, je vais donc désactiver le protocole en attendant la V2.
Comme je ne veux pas faire de bêtises, je préfère confirmation avant : suffit-il de passer le champ `actif` de la table `meta.bib_programmes` de `TRUE` à `FALSE` ?

Du coup, je vais ajouter les taxons bryophytes + champignons au Contact Flore (je pense pouvoir y arriver seul). Est-il facile de renommer les protocoles visibles dans l'interface utilisateur ? (je mettrais bien "Contact Plantes et Champignons")

**Comment by sig-pnrnm** [comment]
> Ça pose d'ailleurs la question, si dans la V2 on met "Prénom NOM" ou "NOM Prénom" ?

Pas d'avis sur la question, sauf qu'il faudra être homogène avec les autres protocoles. Actuellement, tous les autres sont sur "Nom Prénom".

**Comment by camillemonchicourt** [comment]
Ce champs permet juste de gérer le COMMENT du module de RECHERCHE de SYNTHÈSE : https://github.com/PnEcrins/GeoNature/issues/67

Les boutons affichés sur la HOME de GeoNature sont basés sur `synthese.bib_sources` : https://github.com/PnEcrins/GeoNature/issues/69

Je ne sais plus si en changeant le nom de la source, cela change le nom du bouton sur la HOME de GeoNature. 

Oui pour les noms et prenoms dans la Synthèse, il faut que cela soit homogène. Si il y a le PB d'ordre dans Bryophytes, c'est fort possible que cela soit pareil dans le trigger qui alimente la Synthèse à partir de Flore Station.

**Comment by gildeluermoz** [comment]
J'ai retenu NOM PRENOM : bd457e6ca2d3482b2f172c5ef4142816c5a5f1b9
Correction Bryophyhes et flore station

**Comment by sig-pnrnm** [comment]
> Je ne sais plus si en changeant le nom de la source, cela change le nom du bouton sur la HOME de GeoNature.

Pour répondre à cette question, oui ça marche !

Par contre, je ne sais si cela a un lien, mais j'ai un comportement étrange de la synthèse depuis que j'ai touché aux tables `meta.bib_programmes` (`actif=false` sur programme Bryophytes) et `synthese.bib_sources` (renommages `nom_source`* et `actif=false` pour programme "Bryophytes") : nous ne pouvons plus modifier les données Contact vertébrés depuis la synthèse ??

Une idée de ce qui a pu causer ce changement ?

_* Passage de `Contact faune` à `Contact Faune` (F majuscule), ou de `Contact flore` à `Contact Flore et Bryophytes` par exemple._

**Comment by camillemonchicourt** [comment]
Oui on voit que `Contact faune` est en dur à quelques endroits dans le code : https://github.com/PnEcrins/GeoNature/search?utf8=%E2%9C%93&q=Contact+faune&type=

Changer le nom dans la BDD doit poser des soucis.

**Comment by sig-pnrnm** [comment]
Aïe, dans ce cas, c'est sûr qu'il ne faut pas modifier les noms... (à revoir je suppose en V2 pour plus de "généricité" ?)
Mais chose étrange, j'ai beau avoir renommé comme avant les protocoles, un collègue ne peut modifier certaines de ses données saisies dans Contact-Faune. Il peut en modifier certaines (comportement normal), mais pas toutes... ?!

Une idée d'où ça peut venir ?

_(je sors du sujet initial qui concernait le protocole Bryophites : je rouvre une issue ?)_

**Comment by gildeluermoz** [comment]
Effectivement, le trigger ``contactfaune.synthese_insert_releve_cf()`` utilise le nom de la source en dur. Il n'est pas possible de mettre cette information en variable car il s'agit de récupérer l'id source à partir des informations de la table bib_sources. Seul le champ ``nom_source`` permet de distinguer ``Mortalité`` du ``Contact faune``.
Seuls ces deux protocoles sont concernés. Si tu renommes d'autres protocoles, ça ne devrait pas bugguer. Par contre ca va générer de l'incohérence de nommage car le nom du protocole n'est pas prévu pour être paramètrable.
Pour les données non modifiables, il faut regarder dans la table ``synthese.syntheseff``, je pense que du coup, pour les données saisies après modification du nom du protocole, le id_source n'a pas été renseigné correctement par le trigger. Il faut les corriger manuellement.

**Comment by sig-pnrnm** [comment]
Merci Gil.
J'avais effectivement des données dans `synthese.syntheseff` sans `id_source` : c'est corrigé et rentré dans l'ordre.
