### ISSUE TITLE
Restaurer les statistiques sur la page d'accueil

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature#24]

**Comment by gildeluermoz** [comment]
Temporairement désactivé

**Comment by camillemonchicourt** [comment]
A voir un intègre un système de stats plus générique sur les protocoles intégrés par défaut. Activable ou non dans les paramètres.
Ou si on fait un système plus personnalisable, par exemple sous forme d'iframe où chacun y intègre ce qu'il veut...
La solution 1 me parait le plus intéressante.

**Comment by gildeluermoz** [comment]
oui pour la solution 1. Le système PNE actuel est basé sur l'alimentation de tables avec le cron du serveur et necessite une remise à jour de certains éléments chaque 1er janvier. Il faut réfléchir à qq chose de plus simple.

**Comment by camillemonchicourt** [comment]
Oui on peut faire un truc plus générique. 
Par exemple le nombre de données par Programmes et par années.
Le nombre de données par années par grand groupe d’espèces
...

**Comment by camillemonchicourt** [comment]
Retour de Donovan : 

* Nombre total de taxons connus par groupes (oiseaux, insectes etc ou à un autre rang, papillons, etc) en se basant sur les cd_ref. 
* Nombre de taxons protégés dans ces groupes et nombre de taxons patrimoniaux (tu verras, 35% pour les vertébrés, 15 pour les plantes, près de 15 pour les invertébrés etc, selon les méthodes qui ont été appliquées)

Et intéressant aussi je pense, nombre de données par classe d'altitude et par grands milieux (alpages, forêts etc) pour mettre en avant les disparités en termes de prospections. Juste pour orienter les agents dont certains chercheront peut être à rétablir un certain équilibre en rentrant des données dans les zones boisées en vallées, qui sont je pense bien bien moins prospectées. 

![nombre donnees par an-1](https://cloud.githubusercontent.com/assets/4418840/10971109/da44e18a-83d2-11e5-93dc-c674bd47ab83.png)


![rplot01-1](https://cloud.githubusercontent.com/assets/4418840/10971111/dd8975a4-83d2-11e5-98e6-54f0b928d8d0.png)

**Comment by camillemonchicourt** [comment]
Si on veut le nombre de données par protocoles, on peut faire : 

- Nombre de données dans la synthèse par source : 

```SQL
SELECT count (sy.id_synthese), so.nom_source, sy.id_source FROM synthese.syntheseff sy
JOIN synthese.bib_sources so on so.id_source = sy.id_source
GROUP by sy.id_source, so.nom_source;
```

- Nombre de données dans la synthèse par programme : 

```SQL
SELECT pr.nom_programme, count (sy.id_synthese), pr.id_programme FROM synthese.syntheseff sy
JOIN meta.bib_lots lo ON lo.id_lot = sy.id_lot
JOIN meta.bib_programmes pr ON pr.id_programme = lo.id_programme
GROUP by pr.id_programme, pr.nom_programme;
```

- Nombre de données par source par année : 

```SQL
SELECT so.nom_source, count (sy.id_synthese), sy.id_source, EXTRACT(YEAR FROM dateobs) as annee FROM synthese.syntheseff sy
JOIN synthese.bib_sources so on so.id_source = sy.id_source
GROUP by sy.id_source, so.nom_source, annee;
```

- Nombre de données par programme par année : 

```SQL
SELECT pr.nom_programme, count (sy.id_synthese), pr.id_programme, EXTRACT(YEAR FROM dateobs) as annee FROM synthese.syntheseff sy
JOIN meta.bib_lots lo ON lo.id_lot = sy.id_lot
JOIN meta.bib_programmes pr ON pr.id_programme = lo.id_programme
GROUP by pr.id_programme, pr.nom_programme, annee
ORDER by pr.nom_programme, annee DESC;
```

En faisant par année, on peut générer un graphique de ce type : 

![synthese-stats](https://cloud.githubusercontent.com/assets/4418840/11659383/5327f632-9dc8-11e5-8a6b-8dc840e405f1.jpg)

**Comment by camillemonchicourt** [comment]
NOMBRE DE DONNEES PAR REGNE : 

```SQL
SELECT tr.regne, count(*) FROM synthese.syntheseff s
JOIN taxonomie.taxref tr ON tr.cd_nom = s.cd_nom
WHERE s.supprime = false
GROUP BY tr.regne
```

Limiter à une structure : 

```SQL
SELECT tr.regne, count(*) FROM synthese.syntheseff s
JOIN taxonomie.taxref tr ON tr.cd_nom = s.cd_nom
WHERE s.supprime = false AND s.id_organisme = 2
GROUP BY tr.regne
```

NOMBRE DE DONNEES PAR CLASSE :

```SQL
SELECT tr.classe, count(*) FROM synthese.syntheseff s
JOIN taxonomie.taxref tr ON tr.cd_nom = s.cd_nom
WHERE s.supprime = false
GROUP BY tr.classe
```

Limiter à une structure : 

```SQL
SELECT tr.classe, count(*) FROM synthese.syntheseff s
JOIN taxonomie.taxref tr ON tr.cd_nom = s.cd_nom
WHERE s.supprime = false  AND s.id_organisme = 2
GROUP BY tr.classe
```

NOMBRE DE DONNEES PAR GROUPE en se basant sur les listes créées dans la taxonomie (TaxHub) : 

```SQL
SELECT l.nom_liste, count(*) FROM synthese.syntheseff s
JOIN taxonomie.taxref tx ON tx.cd_nom = s.cd_nom
JOIN taxonomie.bib_taxons t ON t.cd_nom = tx.cd_nom
LEFT JOIN taxonomie.cor_taxon_liste ctl ON ctl.id_taxon = t.id_taxon
LEFT JOIN taxonomie.bib_listes l ON l.id_liste = ctl.id_liste
WHERE s.supprime = false
GROUP BY nom_liste,l.id_liste
ORDER BY l.id_liste
```

**Comment by gildeluermoz** [comment]
à enrichir sur la base du modèle mise en place

**Comment by camillemonchicourt** [comment]
Nombre de taxons observés par classe.
