### ISSUE TITLE
Dépersonalisation

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoNature#29]
Nombreuses actions à conduire progressivement: 
 - interface
 - nom des variables, champs  ...

**Comment by camillemonchicourt** [comment]
Ça avance avec le regroupement Faune et Flore dans la 1.3.0, le passage à TaxHub dans la 1.4.0 et la possibilité de désactiver des protocoles dans la 1.5.0.
Plus de la documentation.

**Comment by gildeluermoz** [comment]
La dépersonnalisation est bien avancée, faire désormais des tickets spécifiques.
