### ISSUE TITLE
Revoir le nom de l'application

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#31]
Faune-Flore ? Vu que l'application intègre la synthèse mais aussi les BDD et saisie des protocoles sources ???? 

La SYNTHESE n'est qu'une partie de l'appli qui regroupe aussi les données des protocoles sources en aval et les exports vers les partenaires en aval.

**Comment by Chrispnv** [comment]
Salut,
1e connexion pour tester

**Comment by gildeluermoz** [comment]
ben ça marche ! 
welcome on github ! 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "CHILLET Christophe" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Mardi 6 Janvier 2015 14:50:16 
Objet: Re: [GeoNature] Revoir le nom de l'application (#31) 


Salut, 
1e connexion pour tester

**Comment by gildeluermoz** [comment]
GeoNature.
DONE
