### ISSUE TITLE
Utiliser le parametre du nom de l'application SYNTHESE

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#40]
Par exemple à cette ligne du document : https://github.com/PnEcrins/GeoNature/blob/a64d83b96bb8d1d4de898a6f5c6e1db6526ff8bf/web/js/cf/application.cf.editFiche.js#L1929

Trouvé en recherchant "faune" dans le Github : https://github.com/PnEcrins/GeoNature/search?l=javascript&q=faune&utf8=%E2%9C%93

**Comment by gildeluermoz** [comment]
Il n'y a pas de paramètre avec le nom de l'application.
GeoNature est un nom global regroupant le contact faune, mortalité, contact invertébré, synthèse et d'autre pour la flore.
Il n'y pas d'intéret particulier à mettre ces noms en paramètre. 
Par contre j'ai retirer les références à "synthèse faune". Remplacé par "synthèse"
