### ISSUE TITLE
Généricité du style

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#55]
Bandeau de la page d'accueil
Nom de l'application et structure indiqué sur la page d'accueil
....

**Comment by camillemonchicourt** [comment]
Les noms de l'application sont déjà paramétrables : https://github.com/PnEcrins/GeoNature/blob/48163ff464a8e20e7346130992483d17e5a05bdf/lib/sfGeonatureConfig.php.sample#L53-L62

**Comment by camillemonchicourt** [comment]
Le bandeau est personnalisable aussi. 
Fichier ``web/images/bandeau_faune.jpg``

http://geonature.readthedocs.org/fr/latest/installation.html?highlight=bandeau#mise-a-jour-de-l-application

**Comment by gildeluermoz** [comment]
le bandeau se nomme maintenant bandeau_geonature.jpg
https://github.com/PnEcrins/GeoNature/blob/fa226850b3fb9f9ef7aaa7bf555b2fffbbcb74b8/web/images/bandeau_geonature.jpg

**Comment by gildeluermoz** [comment]
A priori tout est fait dans des commit précédents
