### ISSUE TITLE
BIB_programmes - Ajouter champs ACTIF

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#67]
La table ``meta.bib_programmes`` permet de construire la liste COMMENT dans l'application Synthèse. 
Il serait intéressant d'ajouter un champ ``actif`` dans cette table pour ceux qui n'utilisent pas tous les protocoles de GeoNature pour que certains programmes n'apparaissent pas dans la liste des critères COMMENT. 
Voir https://github.com/PnEcrins/GeoNature/issues/63

**Comment by gildeluermoz** [comment]
closed with commit 2b84966a60482967da4fd5f2557d1e734d08e662
