### ISSUE TITLE
HOME - Construire la liste des protocoles par requête

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#69]
Ça éviterait de modifier le fichier ``apps/frontend/modules/home/template/indexSuccess.php`` à la main et de le maintenir à chaque mise à jour de GeoNature.
Généricité : https://github.com/PnEcrins/GeoNature/issues/54

- Ajouter un champ ``URL`` dans ``synthese.bib_sources``
- Ajouter un champ ``TARGET`` dans ``synthese.bib_sources`` pour ouvrir dans le même onglet ou non (_blank)
- Ajouter un champ ``PICTO`` dans ``synthese.bib_sources`` pour le petit pictogramme devant chaque lien vers l'appli du protocole
- Ajouter un champ ``GROUPE`` dans ``synthese.bib_sources`` pour les regrouper par bloc sur la HOME (par exemple Faune, Flore, Fonge ou Inventaire, Suivi)

**Comment by camillemonchicourt** [comment]
Et comme pour les programmes (https://github.com/PnEcrins/GeoNature/issues/67), ajouter un champs booléen ``ACTIF`` pour ceux qui ne veulent pas utiliser certains protocoles livrés avec GeoNature.
Ainsi ils n'apparaitront pas sur la page d'accueil.

**Comment by gildeluermoz** [comment]
closed by this commit 0bd75e8ac4930e987215df5f5aa198a00a06174e
