### ISSUE TITLE
Problèmes de droits de répertoire qui sont en ROOT

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#70]
Par exemple le fichier ``web/css/main.css`` ainsi que tout ce qui est dans ``web/images/pictos``.
Je pense que c'est du au fait que ça a été commité en root dans Github il y a quelques temps.

**Comment by gildeluermoz** [comment]
j'ai remis les droits à l'utilisateur courant. Tu peux faire les modifs. Je ferai le commit ensuite.

**Comment by camillemonchicourt** [comment]
OK à voir si c'est juste chez nous ou aussi sur les fichiers sur Github.

**Comment by camillemonchicourt** [comment]
Problème uniquement sur serveur PNE. 
Réglé localement.
