### ISSUE TITLE
Généricité des visuels

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#75]
Supprimer la spirale violette en fond des formulaires de chargement et de login.
Revoir les bandeaux PNE des applications Flore.

Ou du moins documenter la possibilité de les changer.

**Comment by gildeluermoz** [comment]
Oui, j'ai mis vite fait qq chose en fond sans ajouter d'image, sur le modèle de la page de login.
Je te laisse revoir ça.

**Comment by gildeluermoz** [comment]
on peut fermer ce ticket non ?

**Comment by camillemonchicourt** [comment]
Oui !
