### ISSUE TITLE
Déplacer conditions utilisations IGN sur les cartes

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#76]
A mettre en dessous de "Provided by IGN".

**Comment by camillemonchicourt** [comment]
C'est comme ça dans Synthese

**Comment by camillemonchicourt** [comment]
OK du coup dans Bryophytes et FS c'est en bas à gauche de la carte, sur Synthese c'est en bas centré. 

Mais c'est mieux en effet. 

Merci !

**Comment by gildeluermoz** [comment]
j'ai juste ajouté le css de l'api geoportail qui manquait. je ne sais pas pourquoi ça ne s'affiche pas partout pareil. Certainement d'autre css qui interfère. 

On va dire que c'est bon ! 



		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Jeudi 12 Novembre 2015 15:14:49 
Objet: Re: [GeoNature] Déplacer conditions utilisations IGN sur les cartes (#76) 


OK du coup dans Bryophytes et FS c'est en bas à gauche de la carte, sur Synthese c'est en bas centré. 
Mais c'est mieux en effet. 
Merci !
