### ISSUE TITLE
Title de l'appli paramétrable avant login

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#77]
Avant d'être loggué, le title de l'appli est en dur : https://github.com/PnEcrins/GeoNature/blob/master/apps/backend/modules/home/actions/actions.class.php#L11

Une fois loggué il utilise bien la variable "$appname_main".

Voir https://github.com/PnEcrins/GeoNature/issues/55

**Comment by gildeluermoz** [comment]
closed by this commit 030eacc9415fb9c52324c61d602a16dbccde6628
