### ISSUE TITLE
Export SHP renvoie des fichiers vides

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#80]
Version 1.5.0dev0 de GeoNature dans la Synthèse. Idem sur les protocoles flore ?

**Comment by gildeluermoz** [comment]
ce problème est spécifique à la configuration PNE avec le serveur d'application hergeant une version de gdal compatible avec postgis 1.5  mais le serveur de base de données et en postgis 2. du coup OGR2OGR sur le serveur applicatif est en GDAL 1.9.0 et il renvoie une erreur "la fonction getsrid(geometry) n'existe pas". A priori GDAL 1.10 est requis.
