### ISSUE TITLE
HOME - Ajouter pied de page

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#83]
Lire et afficher le fichier mentionnant le numéro de version et l'afficher dans le pied de page. 
Ajouter le copyright "GeoNature, développé par le Parc national des Ecrins" ainsi qu'un bouton de Deconnexion.

**Comment by camillemonchicourt** [comment]
Beautiful !

**Comment by gildeluermoz** [comment]
J'ai boostrapé tout ça. Je te laisse peaufiner l'affaire avant de faire un commit ! 
http://portail.ecrins-parcnational.fr/geonature/ 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Jeudi 12 Novembre 2015 17:32:32 
Objet: Re: [GeoNature] HOME - Ajouter pied de page (#83) 


Beautiful !

**Comment by camillemonchicourt** [comment]
Ouais OK, y a des petites choses que j'aimerai bien ajuster mais je ne suis pas bien sur quels fichiers je peux intervenir.
Je pense qu'il ne faut pas intervenir sur les fichiers bootstrap mais juste sur les surcouches mais je voudrai voir comment tu as fait.

**Comment by gildeluermoz** [comment]
Tu peux jouer sur le main.css dans la partie que tu avais créée notamment : /* HOME GeoNature */ 
le fichier de template est le /var/www/localhost/private/trunk/geonature/apps/backend/modules/home/templates/indexSuccess.php 
Effectivement, il ne faut pas toucher le css de bootstrap mais plutôt le surcoucher si besoin. 

Bon courage pour cette formation 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Vendredi 13 Novembre 2015 21:34:19 
Objet: Re: [GeoNature] HOME - Ajouter pied de page (#83) 


Ouais OK, y a des petites choses que j'aimerai bien ajuster mais je ne suis pas bien sur quels fichiers je peux intervenir. 
Je pense qu'il ne faut pas intervenir sur les fichiers bootstrap mais juste sur les surcouches mais je voudrai voir comment tu as fait.
