### ISSUE TITLE
SYNTHESE - Rechercher un taxon, afficher les synonymes ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#92]
Si je recherche un taxon, est-ce que je requête sur le CD_nom, ou alors sur le CD_ref auquel cas j'aurai tous les synonymes du taxon ?

**Comment by camillemonchicourt** [comment]
Après avoir fait le tour des chargés de mission faune et flore, voila ce qui ressort : 
- Il faut saisir et rechercher sur le CD_nom mais requêter sur le CD_ref pour afficher les synonymes. 
- Dans les résultats, n'afficher que le nom de référence ? Ou plutôt afficher les CD_nom mais pouvoir afficher le CD_ref et le nom valide.

**Comment by gildeluermoz** [comment]
Les résultats affichent désormais tous les synonymes. 
Les exports xls et shp comportent le cd_nom ET le cd_ref de tous les synonymes du nom recherché ainsi que le nom_latin (bib_taxons) ET le nom_valide (taxref).
Pour l'affichage du tableau de résultats dans la synthèse de GeoNature la clause where est construite avec une sous requête (proposée par Julien)
Pour les exports, la sous requête pose un pb important de performance (10s pour 30 lignes). La fonction taxonomie.find_cdref(cd_nom) est utilisée (500ms pour 30 lignes).

**Comment by camillemonchicourt** [comment]
Cool, mais du coup pourquoi utiliser la sous requête si elle est beaucoup plus longue ?

**Comment by gildeluermoz** [comment]
Dans un cas (affichage résultats synthèse) elle n'est pas pénalisante, dans l'autre (export) oui #:-S Je ne sais pas pourquoi. 
Dans le cas d'une recherche sur plusieurs taxons, la fonction find_cdref(cd_nom) ne prend qu'un cd_nom et donc je ne peux pas la mettre dans une clause "IN" --> donc sous requête obligatoire. 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Mercredi 30 Décembre 2015 16:25:36 
Objet: Re: [GeoNature] SYNTHESE - Rechercher un taxon, afficher les synonymes ? (#92) 


Cool, mais du coup pourquoi utiliser la sous requête si elle est beaucoup plus longue ?
