### ISSUE TITLE
Symfony 1.4.6 incompatible avec PHP 5.6

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#96]
Or c'est cette version de PHP qui est livrée avec Debian 8. 
Donc pour le moment GeoNature ne fonctionne qu'avec Debian 7 livrée avec PHP 5.4.

**Comment by gildeluermoz** [comment]
Le soucis sur le serveur de test du PNM était lié à un oubli dans la conf apache.
Le commit précédent corrige l'affichage des notices consernant les fonctions dépréciées de symfony 1.4 avec php 5.6.
