### ISSUE TITLE
Synthese - Critere Faune / Flore / Fonge / Tout ne filtre pas la liste des taxons

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoNature#98]
Je coche Flore, puis cherche Lagopède alpin dans la liste des taxons et celui-ci apparaît. 
Mais la recherche ne renvoie aucun résultats. 

A noter aussi, Donovan sous Mac avec Safari recherche TOUT avec taxon Lagopède alpin entre 1900 et 2015 et ça ne lui renvoie aucun résultats. Moi ça m'en retourne bien 2850 sur PC avec Chrome...
Et ça marche sur son MAC avec Firefox... Donc problème Safari ???

**Comment by gildeluermoz** [comment]
je bosse là dessus 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Envoyé: Mercredi 16 Décembre 2015 10:56:25 
Objet: [GeoNature] Synthese - Critere Faune / Flore / Fonge / Tout ne filtre pas la liste des taxons (#98) 


Je coche Flore, puis cherche Lagopède alpin dans la liste des taxons et celui-ci apparaît 
Mais la recherche ne renvoie aucun résultats 
A noter aussi, Donovan sous Mac avec Safari recherche TOUT avec taxon Lagopède alpin entre 1900 et 2015 et ça ne lui renvoie aucun résultats Moi ça m'en retourne bien 2850 sur PC avec Chrome 
Et ça marche sur son MAC avec Firefox Donc problème Safari ???

**Comment by gildeluermoz** [comment]
Or Safari, je vois le soucis. Lorsque le store est filtré (faune, flore faune, patri, protégés...), si on tape qq chose dans le combo, le filtre saute.
C'est une grosse modification. Soit :
1 - Il ne faut plus filtrer le store mais le recharger sur la bse des paramètres transmis.
OU
2 - il faut supprimer tous les filtres si l'utilisateur tape qq chose dans le combo.
Je trouve la solution 1 plus respectueuse des choix de l'utilisateur.

**Comment by camillemonchicourt** [comment]
Oui solution 1. Si je limite à la flore ou aux espèces patrimoniales, ça doit réduire la liste des taxons. Que je parcours cette liste ou que je saisisse directement le taxon que j'ai en tête. 

Pour le problème spécifique Safari, j'ai ouvert un autre ticket - https://github.com/PnEcrins/GeoNature/issues/100

**Comment by gildeluermoz** [comment]
j'y bosse mais c'est du lourd, comme je m'y attendais ! 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0)4 92 21 08 49 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "gildeluermoz" <gil.deluermoz@ecrins-parcnational.fr> 
Envoyé: Mercredi 16 Décembre 2015 13:29:31 
Objet: Re: [GeoNature] Synthese - Critere Faune / Flore / Fonge / Tout ne filtre pas la liste des taxons (#98) 


Oui solution 1. Si je limite à la flore ou aux espèces patrimoniales, ça doit réduire la liste des taxons. Que je parcours cette liste ou que je saisisse directement le taxon que j'ai en tête. 
Pour le problème spécifique Safari, j'ai ouvert un autre ticket - #100

**Comment by camillemonchicourt** [comment]
OK mais c'est pas super grave ni urgent. C'est une évolution mineure. 

Le coup du CD_ref par exemple c'est bien plus utile : https://github.com/PnEcrins/GeoNature/issues/92

**Comment by gildeluermoz** [comment]
reste #100
